# Generated by Django 4.2.28 on 2026-02-19 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_miles_today', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=500)),
                ('pickup_location', models.CharField(max_length=500)),
                ('dropoff_location', models.CharField(max_length=500)),
                ('cycle_used_hours', models.FloatField(help_text='Hours already used in the 70/8 cycle')),
                ('routing_provider', models.CharField(default='openrouteservice', max_length=50)),
                ('total_miles', models.FloatField(default=0)),
                ('total_drive_minutes', models.IntegerField(default=0)),
                ('route_polyline', models.TextField(blank=True, default='', help_text='Encoded polyline geometry')),
                ('current_location_lat', models.FloatField(default=0)),
                ('current_location_lng', models.FloatField(default=0)),
                ('pickup_location_lat', models.FloatField(default=0)),
                ('pickup_location_lng', models.FloatField(default=0)),
                ('dropoff_location_lat', models.FloatField(default=0)),
                ('dropoff_location_lng', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('FUEL', 'Fuel Stop'), ('BREAK_30', '30-Min Break'), ('OFF_DUTY_10', '10-Hour Off Duty'), ('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff')], max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('label', models.CharField(blank=True, default='', max_length=500)),
                ('start_minute_global', models.IntegerField(help_text='Minutes since trip start when this stop begins')),
                ('duration_minutes', models.IntegerField()),
                ('trip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.tripplan')),
            ],
            options={
                'ordering': ['start_minute_global'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_minute', models.IntegerField(help_text='0–1440, minutes from midnight')),
                ('end_minute', models.IntegerField(help_text='0–1440, minutes from midnight')),
                ('status', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('SLEEPER', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY_NOT_DRIVING', 'On Duty (Not Driving)')], max_length=25)),
                ('location_label', models.CharField(blank=True, default='', max_length=500)),
                ('daily_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.dailysheet')),
            ],
            options={
                'ordering': ['start_minute'],
            },
        ),
        migrations.AddField(
            model_name='dailysheet',
            name='trip_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sheets', to='trips.tripplan'),
        ),
    ]
