# Generated by Django 4.2.28 on 2026-02-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='planned_fuel_stops',
            field=models.IntegerField(default=0, help_text='Total fuel stops needed for the full route'),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='remaining_drive_minutes',
            field=models.IntegerField(default=0, help_text='Minutes of driving remaining if trip is incomplete'),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='trip_completed',
            field=models.BooleanField(default=True, help_text='Whether the driver can complete the full trip'),
        ),
    ]
